// meu-pdi-angular/src/app/auth/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, AbstractControl } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrl: './register.component.scss'
})
export class RegisterComponent implements OnInit {
  registerForm!: FormGroup;
  isLoading = false;
  errorMessage = '';
  hidePassword = true;
  hideConfirmPassword = true;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.initForm();
  }

  private initForm(): void {
    this.registerForm = this.fb.group({
      name: ['', [Validators.required, Validators.minLength(2)]],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
      confirmPassword: ['', [Validators.required]],
      acceptTerms: [false, [Validators.requiredTrue]]
    }, {
      validators: this.passwordMatchValidator
    });
  }

  private passwordMatchValidator(control: AbstractControl): { [key: string]: any } | null {
    const password = control.get('password');
    const confirmPassword = control.get('confirmPassword');

    if (password && confirmPassword && password.value !== confirmPassword.value) {
      return { passwordMismatch: true };
    }
    return null;
  }

  onSubmit(): void {
    if (this.registerForm.valid) {
      this.isLoading = true;
      this.errorMessage = '';

      const { name, email, password } = this.registerForm.value;

      this.authService.register({ name, email, password }).subscribe({
        next: (response) => {
          this.isLoading = false;
          // TASK-ARCH002: Migrar Componentes Core Auth - Registro implementado
          this.router.navigate(['/dashboard']);
        },
        error: (error) => {
          this.isLoading = false;
          this.errorMessage = error.error?.message || 'Erro ao criar conta. Tente novamente.';
        }
      });
    } else {
      this.markFormGroupTouched();
    }
  }

  private markFormGroupTouched(): void {
    Object.keys(this.registerForm.controls).forEach(key => {
      const control = this.registerForm.get(key);
      control?.markAsTouched();
    });
  }

  get name() {
    return this.registerForm.get('name');
  }

  get email() {
    return this.registerForm.get('email');
  }

  get password() {
    return this.registerForm.get('password');
  }

  get confirmPassword() {
    return this.registerForm.get('confirmPassword');
  }

  get acceptTerms() {
    return this.registerForm.get('acceptTerms');
  }
}

<div class="register-container">
  <div class="register-card">
    <div class="register-header">
      <h1 class="register-title">Criar Conta</h1>
      <p class="register-subtitle">Junte-se à nossa plataforma de desenvolvimento profissional</p>
    </div>

    <form [formGroup]="registerForm" (ngSubmit)="onSubmit()" class="register-form">
      <!-- Name Field -->
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Nome Completo</mat-label>
        <input matInput
               type="text"
               formControlName="name"
               placeholder="Digite seu nome completo"
               autocomplete="name">
        <mat-icon matSuffix>person</mat-icon>
        <mat-error *ngIf="name?.invalid && name?.touched">
          <span *ngIf="name?.errors?.['required']">Nome é obrigatório</span>
          <span *ngIf="name?.errors?.['minlength']">Nome deve ter pelo menos 2 caracteres</span>
        </mat-error>
      </mat-form-field>

      <!-- Email Field -->
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Email</mat-label>
        <input matInput
               type="email"
               formControlName="email"
               placeholder="seu@email.com"
               autocomplete="email">
        <mat-icon matSuffix>email</mat-icon>
        <mat-error *ngIf="email?.invalid && email?.touched">
          <span *ngIf="email?.errors?.['required']">Email é obrigatório</span>
          <span *ngIf="email?.errors?.['email']">Email inválido</span>
        </mat-error>
      </mat-form-field>

      <!-- Password Field -->
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Senha</mat-label>
        <input matInput
               [type]="hidePassword ? 'password' : 'text'"
               formControlName="password"
               placeholder="Digite sua senha"
               autocomplete="new-password">
        <button mat-icon-button matSuffix (click)="hidePassword = !hidePassword" type="button">
          <mat-icon>{{hidePassword ? 'visibility_off' : 'visibility'}}</mat-icon>
        </button>
        <mat-error *ngIf="password?.invalid && password?.touched">
          <span *ngIf="password?.errors?.['required']">Senha é obrigatória</span>
          <span *ngIf="password?.errors?.['minlength']">Senha deve ter pelo menos 6 caracteres</span>
        </mat-error>
      </mat-form-field>

      <!-- Confirm Password Field -->
      <mat-form-field appearance="outline" class="full-width">
        <mat-label>Confirmar Senha</mat-label>
        <input matInput
               [type]="hideConfirmPassword ? 'password' : 'text'"
               formControlName="confirmPassword"
               placeholder="Confirme sua senha"
               autocomplete="new-password">
        <button mat-icon-button matSuffix (click)="hideConfirmPassword = !hideConfirmPassword" type="button">
          <mat-icon>{{hideConfirmPassword ? 'visibility_off' : 'visibility'}}</mat-icon>
        </button>
        <mat-error *ngIf="confirmPassword?.invalid && confirmPassword?.touched">
          <span *ngIf="confirmPassword?.errors?.['required']">Confirmação de senha é obrigatória</span>
        </mat-error>
        <mat-error *ngIf="registerForm?.errors?.['passwordMismatch'] && confirmPassword?.touched">
          As senhas não coincidem
        </mat-error>
      </mat-form-field>

      <!-- Terms and Conditions -->
      <mat-checkbox formControlName="acceptTerms" class="terms-checkbox">
        <span class="terms-text">
          Li e concordo com os
          <a href="/terms" target="_blank" class="terms-link">Termos de Uso</a> e
          <a href="/privacy" target="_blank" class="terms-link">Política de Privacidade</a>
        </span>
      </mat-checkbox>
      <mat-error *ngIf="acceptTerms?.invalid && acceptTerms?.touched" class="terms-error">
        Você deve aceitar os termos para continuar
      </mat-error>

      <!-- Error Message -->
      <div *ngIf="errorMessage" class="error-message">
        <mat-icon>error</mat-icon>
        <span>{{ errorMessage }}</span>
      </div>

      <!-- Submit Button -->
      <button mat-raised-button
              color="primary"
              type="submit"
              class="register-button"
              [disabled]="isLoading || registerForm.invalid">
        <mat-spinner diameter="20" *ngIf="isLoading"></mat-spinner>
        <span *ngIf="!isLoading">Criar Conta</span>
        <span *ngIf="isLoading">Criando conta...</span>
      </button>

      <!-- Links -->
      <div class="register-links">
        <span>Já tem uma conta?</span>
        <a routerLink="/auth/login" class="link">Fazer login</a>
      </div>
    </form>
  </div>
</div>

// src/frontend/src/app/auth/register/page.tsx
'use client'

import { useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'

export default function RegisterPage() {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: '',
    confirmPassword: '',
    acceptTerms: false
  })
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState('')
  const router = useRouter()

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value, type, checked } = e.target
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }))
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsLoading(true)
    setError('')

    // Validações básicas
    if (formData.password !== formData.confirmPassword) {
      setError('As senhas não coincidem.')
      setIsLoading(false)
      return
    }

    if (!formData.acceptTerms) {
      setError('Você deve aceitar os termos de uso.')
      setIsLoading(false)
      return
    }

    try {
      // TODO: Implementar chamada para API de registro
      console.log('Register attempt:', formData)

      // Simulação de registro bem-sucedido
      await new Promise(resolve => setTimeout(resolve, 1500))

      // Redirecionar para página de confirmação de email
      router.push('/auth/register-success')
    } catch (err) {
      setError('Erro ao criar conta. Tente novamente.')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
            Criar sua conta
          </h2>
          <p className="mt-2 text-center text-sm text-gray-600">
            Já tem uma conta?{' '}
            <Link
              href="/auth/login"
              className="font-medium text-indigo-600 hover:text-indigo-500"
            >
              Faça login
            </Link>
          </p>
        </div>

        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          <div className="rounded-md shadow-sm -space-y-px">
            <div>
              <label htmlFor="name" className="sr-only">
                Nome completo
              </label>
              <input
                id="name"
                name="name"
                type="text"
                autoComplete="name"
                required
                className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                placeholder="Nome completo"
                value={formData.name}
                onChange={handleChange}
              />
            </div>
            <div>
              <label htmlFor="email" className="sr-only">
                Email
              </label>
              <input
                id="email"
                name="email"
                type="email"
                autoComplete="email"
                required
                className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                placeholder="Endereço de email"
                value={formData.email}
                onChange={handleChange}
              />
            </div>
            <div>
              <label htmlFor="password" className="sr-only">
                Senha
              </label>
              <input
                id="password"
                name="password"
                type="password"
                autoComplete="new-password"
                required
                className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                placeholder="Senha (mínimo 8 caracteres)"
                value={formData.password}
                onChange={handleChange}
              />
            </div>
            <div>
              <label htmlFor="confirmPassword" className="sr-only">
                Confirmar senha
              </label>
              <input
                id="confirmPassword"
                name="confirmPassword"
                type="password"
                autoComplete="new-password"
                required
                className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                placeholder="Confirmar senha"
                value={formData.confirmPassword}
                onChange={handleChange}
              />
            </div>
          </div>

          <div className="flex items-center">
            <input
              id="acceptTerms"
              name="acceptTerms"
              type="checkbox"
              className="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
              checked={formData.acceptTerms}
              onChange={handleChange}
            />
            <label htmlFor="acceptTerms" className="ml-2 block text-sm text-gray-900">
              Aceito os{' '}
              <Link href="/terms" className="text-indigo-600 hover:text-indigo-500">
                Termos de Uso
              </Link>{' '}
              e{' '}
              <Link href="/privacy" className="text-indigo-600 hover:text-indigo-500">
                Política de Privacidade
              </Link>
            </label>
          </div>

          {error && (
            <div className="text-red-600 text-sm text-center">
              {error}
            </div>
          )}

          <div>
            <button
              type="submit"
              disabled={isLoading}
              className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isLoading ? 'Criando conta...' : 'Criar conta'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
